version: '2'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    volumes:
      - $PWD/data/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - $PWD/data/grafana:/var/lib/grafana
  storage:
    image: ghcr.io/openzipkin/zipkin-mysql
    container_name: mysql
    network_mode: host
  zipkin:
    image: ghcr.io/openzipkin/zipkin
    container_name: zipkin
    network_mode: host
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=localhost
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - storage
volumes:
  data:
    external: true
